services:
    server1:
        build: docker1
        container_name: mini_server
    server2:
        image: nginx
        container_name: app
        ports:
            - 80:8080
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf